version: '3.8'
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres
    volumes:
      - postgress_volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_app
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres_db:5432/postgres?schema=public"
volumes:
  postgress_volume:
    
