version: '3.8'
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    image: attendanceapp
    container_name: attendance_app
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres_db:password@localhost:5432/postgres?schema=public"
volumes:
  postgres_volume:
    
